### ISSUE TITLE
Message should be urlencoded

### ISSUE THREAD

**Issue by ghost** [ConnectCorp/nexmo-client#1]
As for SMS (known as Message in your implementation), the text should be URL and UTF8 encoded.

I agree with the tradeoff about it's to the developer to ensure the strings are in UTF-8 but i think it should be the library that does the urlencode just before sending data to Nexmo.

What do you think about that ?

**Comment by vood** [comment]
@tsyr2co, I think your concern was addressed in latest release 0.1.0.
