### ISSUE TITLE
Guzzle 6

### ISSUE THREAD

**Issue by o10g** [ConnectCorp/nexmo-client#16]
Is there any chance that you upgrade nexmo-client to the 6-th version of Guzzle?

**Comment by glennjacobs** [comment]
:+1:

**Comment by geekdevs** [comment]
I've created PR here https://github.com/ConnectCorp/nexmo-client/pull/21

**Comment by vood** [comment]
Merged #21

**Comment by geekdevs** [comment]
@vood great! Waiting for new release to add it my projects.
