### ISSUE TITLE
Request parameter format issue

### ISSUE THREAD

**Issue by apeltosa** [ConnectCorp/nexmo-client#18]
When sending SMSs the request parameters are concatenated with underscore:
https://github.com/ConnectCorp/nexmo-client/blob/master/src/Service/Message.php#L96

but Nexmo API says that they should be hyphenated:
https://docs.nexmo.com/api-ref/sms-api/request

e.g. 'client_ref' VS 'client-ref'

Has the API changed or is this a bug?

**Comment by vood** [comment]
This is definitely an api change. Can you check if the underscore works for you and if not please send a PR with a fix.

**Comment by apeltosa** [comment]
Underscore does not work. PR done

**Comment by vood** [comment]
Merged
